FROM node:24

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --ignore-scripts && pnpm rebuild argon2

COPY . .

EXPOSE 5000

CMD ["pnpm", "dev"]